# Test Suite for Simplex Algorithm

The following `.ipynb` file is to generate testcases to test the simplex implementations in this repository.

## Setup

### Prerequisites

In [102]:
%pip install numpy scipy pandas nbformat

import numpy as np
import pandas as pd
import scipy
import nbformat

Note: you may need to restart the kernel to use updated packages.


### Parameters

In [103]:
# Change parameters here
TEST_FILE = 'data/input.csv'    # Path to input file
rng = np.random.default_rng()   # Random number generator
MAX_RANK = 5                    # Maximum rank of A
MAX_VAL = 5                     # Threshold for generation

## Generating $A$, $b$ and $c$

In [104]:
# Rank of matrix (<= MAX_RANK)
n = rng.integers(2,MAX_RANK)
m = rng.integers(n,2*MAX_RANK)

# Generating A
U = rng.integers(-MAX_VAL, MAX_VAL, size=(m,m))
S = np.zeros((m,n))
S[:n, :n] = np.eye(n)
V = rng.integers(-MAX_VAL, MAX_VAL, size=(n,n))
A = U@S@V

# Generating b
b = rng.integers(-MAX_VAL, MAX_VAL, size=(m,))

# Generating c
c = rng.integers(-MAX_VAL, MAX_VAL, size=(n,))

out_df = pd.DataFrame(np.zeros((m+1+n,n+1)))
out_df.iloc[0, :n] = c
out_df.iloc[1:m+1, 0:n] = A
out_df.iloc[1:m+1, n] = b
out_df.iloc[m+1:n+m+1, 0:n] = np.eye(n)
out_df.to_csv(TEST_FILE, index=False)

## Testing

### Scipy Methods

In [105]:
res = scipy.optimize.linprog(c, A_ub=A, b_ub=b)
print(res)

           con: array([], dtype=float64)
 crossover_nit: 0
         eqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
           fun: -0.26666666666666655
       ineqlin:  marginals: array([-0.        , -0.06666667, -0.        , -0.        , -0.        ,
       -0.8       , -0.        , -0.        , -0.        ])
  residual: array([0.55555556, 0.        , 1.17777778, 4.33333333, 1.82222222,
       0.        , 0.26666667, 2.48888889, 7.28888889])
         lower:  marginals: array([ 0. , 15.4, 15.6,  0. ])
  residual: array([0.26666667, 0.        , 0.        , 0.17777778])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: 4
         slack: array([0.55555556, 0.        , 1.17777778, 4.33333333, 1.82222222,
       0.        , 0.26666667, 2.48888889, 7.28888889])
        status: 0
       success: True
         upper:  marginals: array([0., 0., 0., 0.])
  residual: array([inf, inf, inf, inf])
             x: array

### Simplex Algorithm

In [106]:
%run '04/Assignment_4.ipynb'

Note: you may need to restart the kernel to use updated packages.
[ 0.26221319 -0.01407687  0.03099042  0.14280182] 0.4763094200793882
[ 0.24544651  0.00822281 -0.02802829  0.22864721] 0.6381078691423531
[ 0.23770739  0.0841629  -0.20844646  0.45791855] 1.0410256410256395
[ 0.23380713  0.15334448 -0.36560758  0.63528428] 1.3279821627647708
[ 0.24858974  0.16019231 -0.3813141   0.66365385] 1.3885256410256406
